# Use the official Node.js 18 image as the base image
FROM node:18 AS build

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the React app for production
RUN npm run build

# Use a smaller base image for serving the build files
FROM node:18-alpine

# Install serve globally in the second stage
RUN npm install -g serve

# Copy the build files from the previous stage
COPY --from=build /app/build /app/build

# Expose port 3000 to the host
EXPOSE 3000

LABEL org.opencontainers.image.source=https://github.com/jaxcksn/CS3365-MBS

# Command to serve the build files using 'serve'
CMD ["serve", "-s", "/app/build", "-l", "3000"]