FROM python:3.9

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

#ENV FLASK_APP=app.py
#ENV FLASK_ENV=development
#ENV FLASK_DEBUG=1

LABEL org.opencontainers.image.source=https://github.com/jaxcksn/CS3365-MBS

EXPOSE 5050
CMD [ "python", "app.py", "--host=0.0.0.0" ]