FROM python:3.11

WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip wheel
RUN pip install --no-cache-dir -r requirements.txt


COPY . .

LABEL org.opencontainers.image.source=https://github.com/jaxcksn/CS3365-MBS

EXPOSE 5050
CMD [ "python", "app.py", "--host=0.0.0.0" ]