services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: CS3365_Team12
      MYSQL_DATABASE: mbs
    ports:
      - "3306:3306"
    volumes:
      - "mbs_db_data:/var/lib/mysql"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 10s
  flyway:
    image: flyway/flyway
    command: -X migrate
    volumes:
      - ../db/migrations:/flyway/sql
      - ../db/migrations/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev-network
volumes:
  mbs_db_data:
networks:
  dev-network:
    driver: bridge
