services:
  # backend:
  #   build:
  #     context: ../backend
  #     dockerfile: dockerfile
  #   ports:
  #     - "5050:5050"
  #   environment:
  #     - FLASK_ENV=development
  #     - FLASK_DEBUG=1
  #     - DATABASE_URL=mysql://root:root@db:3306/mbs
  #     - PORT=5050
  #   volumes:
  #     - ../backend:/app
  #   depends_on:
  #     - db
  #   networks:
  #     - dev-network
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: CS3365_Team12
      MYSQL_DATABASE: mbs
    ports:
      - "3306:3306"
    volumes:
      - "db_data:/var/lib/mysql"
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-network
volumes:
  db_data:
networks:
  dev-network:
    driver: bridge
