name: CD
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files in the frontend folder
        id: frontend-files-changed
        uses: tj-actions/changed-files@v45
        with:
          files: frontend/**, workflows/cd.yml
          files_ignore: frontend/README.md, frontend/publish.sh

      - name: Get changed files in the backend folder
        id: backend-files-changed
        uses: tj-actions/changed-files@v45
        with:
          files: backend/**, workflows/cd.yml
          files_ignore: backend/README.md, backend/publish.sh

      - name: Check for database changes
        id: db-files-changed
        uses: tj-actions/changed-files@v45
        with:
          files: db/migrations/**, workflows/cd.yml
          files_ignore: db/migrations/flyway.conf db/old.init.sql

      - name: Set up Docker Buildx
        if: steps.frontend-files-changed.outputs.any_changed == 'true' || steps.backend-files-changed.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: "Login to GitHub Container Registry"
        if: steps.frontend-files-changed.outputs.any_changed == 'true' || steps.backend-files-changed.outputs.any_changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push frontend image
        if: steps.frontend-files-changed.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/jaxcksn/cs3365-mbs-frontend:latest ./frontend --push

      - name: Build and push backend image
        if: steps.backend-files-changed.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/jaxcksn/cs3365-mbs-backend:latest ./backend --push

      - name: Deploy to Staging
        if: steps.frontend-files-changed.outputs.any_changed == 'true' || steps.backend-files-changed.outputs.any_changed == 'true'
        run: |
          curl -X POST ${{secrets.SERVER_IP}}?token=${{secrets.SERVER_TOKEN}}
