name: Daily Cleanup
on:
  # every day at 01:30am
  schedule:
    - cron: "30 1 * * *"
  # or manually
  workflow_dispatch:
jobs:
  ghcr-cleanup-image:
    name: ghcr cleanup action
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: cs3365-mbs-frontend,cs3365-mbs-backend
          delete-untagged: true
          token: ${{ secrets.GITHUB_TOKEN }}
