name: Delete Docker Image on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-image:
    name: "Cleanup Docker Images"
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up branch name as tag
        id: get_tag_name
        run: |
          # Use the branch name as the tag, sanitized for Docker
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          TAG_NAME="${BRANCH_NAME//[^a-zA-Z0-9-_.]/-}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-tags: ${{ env.TAG_NAME }}
          packages: cs3365-mbs-frontend,cs3365-mbs-backend
          token: ${{ secrets.GITHUB_TOKEN }}
