name: Build PR

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: "pr_build_${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.check_frontend.outputs.any_changed }}
      backend_changed: ${{ steps.check_backend.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch full history for all branches
        run: git fetch --prune --unshallow

      - name: Get last successful commit
        uses: nickderobertis/last-successful-commit-action@v1
        id: last_successful_commit
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          workflow-id: create_pr_container.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check frontend files changed
        id: check_frontend
        uses: tj-actions/changed-files@v45
        with:
          base_sha: ${{ steps.last_successful_commit.outputs.commit-sha }}
          files: frontend/**
          files_ignore: frontend/README.md, frontend/publish.sh

      - name: Check backend files changed
        id: check_backend
        uses: tj-actions/changed-files@v45
        with:
          base_sha: ${{ steps.last_successful_commit.outputs.commit-sha }}
          files: backend/**
          files_ignore: backend/README.md, backend/publish.sh

  frontend-build:
    needs:
      - check-for-changes
    if: needs.check-for-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up branch name as tag
        id: get_tag_name
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          TAG_NAME="${BRANCH_NAME//[^a-zA-Z0-9-_.]/-}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Build Frontend Image
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/jaxcksn/cs3365-mbs-frontend:${{ env.TAG_NAME }} ./frontend --push

  backend-build:
    needs:
      - check-for-changes
    if: needs.check-for-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up branch name as tag
        id: get_tag_name
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          TAG_NAME="${BRANCH_NAME//[^a-zA-Z0-9-_.]/-}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Build Backend Image
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/jaxcksn/cs3365-mbs-backend:${{ env.TAG_NAME }} ./backend --push
